/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uri.robomatch.interfaces;

import com.uri.robomatch.*;
import java.text.*;
import java.util.*;
import javax.swing.*;

public class CompeticaoJFrame extends javax.swing.JFrame {

    private ArrayList<Equipe> equipes;
    private ArrayList<Prova> provas;
    private ArrayList<Penalidade> penalidades;
    private RoboMatchJFrame roboMatch_frame;
    
    public CompeticaoJFrame(RoboMatchJFrame roboMatchf) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        roboMatch_frame = roboMatchf;
        
        equipes = new ArrayList<Equipe>();
        provas = new ArrayList<Prova>();
        penalidades = new ArrayList<Penalidade>();
        carregarEquipes();
        carregarProvas();
        carregarPenalidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        nome_panel = new javax.swing.JPanel();
        nome_text = new javax.swing.JTextField();
        nome_label = new javax.swing.JLabel();
        data_panel = new javax.swing.JPanel();
        data_text = new javax.swing.JTextField();
        data_label = new javax.swing.JLabel();
        equipes_panel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        equipes_list = new javax.swing.JList<>();
        equipes_label = new javax.swing.JLabel();
        inserir_equipe_button = new javax.swing.JButton();
        provas_panel = new javax.swing.JPanel();
        provas_label = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        provas_list = new javax.swing.JList<>();
        inserir_prova_button = new javax.swing.JButton();
        save_button = new javax.swing.JButton();
        penalidade_panel = new javax.swing.JPanel();
        penalidade_label = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        penalidades_list = new javax.swing.JList<>();
        penalidade_button = new javax.swing.JButton();
        penal_panel = new javax.swing.JPanel();
        penal_tempo = new javax.swing.JTextField();
        penal_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        penal_nome = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome_text.setText("Nome");

        nome_label.setText("Nome da competição");

        javax.swing.GroupLayout nome_panelLayout = new javax.swing.GroupLayout(nome_panel);
        nome_panel.setLayout(nome_panelLayout);
        nome_panelLayout.setHorizontalGroup(
            nome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nome_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_text)
                    .addGroup(nome_panelLayout.createSequentialGroup()
                        .addComponent(nome_label)
                        .addGap(0, 119, Short.MAX_VALUE)))
                .addContainerGap())
        );
        nome_panelLayout.setVerticalGroup(
            nome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nome_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nome_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        data_text.setText("  /  /  ");
        data_text.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                data_textFocusLost(evt);
            }
        });

        data_label.setText("Data de início");

        javax.swing.GroupLayout data_panelLayout = new javax.swing.GroupLayout(data_panel);
        data_panel.setLayout(data_panelLayout);
        data_panelLayout.setHorizontalGroup(
            data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(data_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(data_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data_text, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
                .addGap(0, 15, Short.MAX_VALUE))
        );
        data_panelLayout.setVerticalGroup(
            data_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, data_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(data_label, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(data_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(equipes_list);

        equipes_label.setText("Equipes");

        inserir_equipe_button.setText("+");
        inserir_equipe_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserir_equipe_buttonMouseClicked(evt);
            }
        });
        inserir_equipe_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_equipe_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equipes_panelLayout = new javax.swing.GroupLayout(equipes_panel);
        equipes_panel.setLayout(equipes_panelLayout);
        equipes_panelLayout.setHorizontalGroup(
            equipes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipes_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(equipes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equipes_panelLayout.createSequentialGroup()
                        .addComponent(equipes_label, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inserir_equipe_button))
                    .addGroup(equipes_panelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        equipes_panelLayout.setVerticalGroup(
            equipes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, equipes_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(equipes_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equipes_label)
                    .addComponent(inserir_equipe_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        provas_label.setText("Provas");

        jScrollPane3.setViewportView(provas_list);

        inserir_prova_button.setText("+");
        inserir_prova_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inserir_prova_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout provas_panelLayout = new javax.swing.GroupLayout(provas_panel);
        provas_panel.setLayout(provas_panelLayout);
        provas_panelLayout.setHorizontalGroup(
            provas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provas_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(provas_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inserir_prova_button)
                .addContainerGap())
            .addGroup(provas_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        provas_panelLayout.setVerticalGroup(
            provas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(provas_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(provas_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(provas_label)
                    .addComponent(inserir_prova_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        save_button.setText("Salvar");
        save_button.setToolTipText("");
        save_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                save_buttonMouseClicked(evt);
            }
        });

        penalidade_label.setText("Penalidades");

        jScrollPane4.setViewportView(penalidades_list);

        penalidade_button.setText("+");
        penalidade_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                penalidade_buttonMouseClicked(evt);
            }
        });

        penal_tempo.setText("00:15");
        penal_tempo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                penal_tempoFocusLost(evt);
            }
        });
        penal_tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penal_tempoActionPerformed(evt);
            }
        });

        penal_label.setText("Tempo (-)");

        javax.swing.GroupLayout penal_panelLayout = new javax.swing.GroupLayout(penal_panel);
        penal_panel.setLayout(penal_panelLayout);
        penal_panelLayout.setHorizontalGroup(
            penal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penal_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(penal_label)
                .addGap(44, 44, 44))
            .addGroup(penal_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penal_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        penal_panelLayout.setVerticalGroup(
            penal_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penal_panelLayout.createSequentialGroup()
                .addComponent(penal_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(penal_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setText("Descrição");

        penal_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penal_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(penal_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(penal_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout penalidade_panelLayout = new javax.swing.GroupLayout(penalidade_panel);
        penalidade_panel.setLayout(penalidade_panelLayout);
        penalidade_panelLayout.setHorizontalGroup(
            penalidade_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penalidade_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(penalidade_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(penalidade_panelLayout.createSequentialGroup()
                        .addGroup(penalidade_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(penalidade_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(penalidade_panelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(penalidade_button))
                            .addGroup(penalidade_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(penal_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                    .addComponent(penalidade_label))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        penalidade_panelLayout.setVerticalGroup(
            penalidade_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penalidade_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(penalidade_label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(penalidade_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(penal_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(penalidade_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(penalidade_button))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nome_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(data_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(save_button)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(equipes_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(provas_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addComponent(penalidade_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(data_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(provas_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equipes_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(penalidade_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save_button)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserir_equipe_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_equipe_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inserir_equipe_buttonActionPerformed

    private void inserir_equipe_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserir_equipe_buttonMouseClicked
        EquipeJFrame equipe_frame = new EquipeJFrame(this);
        equipe_frame.setVisible(true);
    }//GEN-LAST:event_inserir_equipe_buttonMouseClicked

    private void inserir_prova_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inserir_prova_buttonMouseClicked
        ProvaJFrame prova_frame = new ProvaJFrame(this);
        prova_frame.setVisible(true);
    }//GEN-LAST:event_inserir_prova_buttonMouseClicked

    private void save_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_save_buttonMouseClicked
        Date data = converterData();
        
        Competicao competicao = new Competicao(nome_text.getText(), data);
        
        for (Equipe equipe : equipes) {
            competicao.setEquipe(equipe);
        }
        
        for (Prova prova : provas) {
            competicao.setProva(prova);
        }
        
        for (Penalidade penalidade : penalidades) {
            competicao.setPenalidade(penalidade);
        }
        
        roboMatch_frame.setCompeticao(competicao);
        roboMatch_frame.carregarCompeticoes();
        this.setVisible(false);
    }//GEN-LAST:event_save_buttonMouseClicked

    private void data_textFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_data_textFocusLost
        if (data_text.getText().indexOf("/") < 0 && data_text.getText().isEmpty() == false)
          data_text.setText(data_text.getText().substring(0, 2) + "/" 
                  + data_text.getText().substring(2, 4) + "/" + data_text.getText().substring(4));
        
        if (data_text.getText().length() < 8 || data_text.getText().length() > 10 
                || data_text.getText().length() == 7 || data_text.getText().length() == 9)
            data_text.setText("");
        
        if (data_text.getText().isEmpty() == false && data_text.getText().length() == 8)
               data_text.setText(data_text.getText().substring(0, 6) + "20" + data_text.getText().substring(6));
    }//GEN-LAST:event_data_textFocusLost

    private void penalidade_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_penalidade_buttonMouseClicked
        int tempo = converterTempo();
        
        Penalidade penalidade = new Penalidade(penal_nome.getText().trim(), tempo);
        System.out.println(penal_nome.getText().trim());
        System.out.println(tempo);
        
        penalidades.add(penalidade);
        carregarPenalidades();
    }//GEN-LAST:event_penalidade_buttonMouseClicked
    
    private int converterTempo() {
        String tempo_string = penal_tempo.getText().trim();
        System.out.println(tempo_string);
        
        if (tempo_string.indexOf(":") < 0)
            tempo_string = tempo_string.substring(0, 2) + ":" + tempo_string.substring(2);
        System.out.println(tempo_string);
        
        int tempo_seg = Integer.parseInt(tempo_string.substring(3, 5));
        int tempo_min = Integer.parseInt(tempo_string.substring(0, 2));
        
        tempo_seg += (tempo_min * 60);
        
        return tempo_seg;
    }   
    
    private void carregarPenalidades() {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        String[] nomes = new String[penalidades.size()];
        nomes = getNomePenalidade();
        for(int i=0; i<nomes.length; i++) {
            listModel.addElement(nomes[i]);
        }
        
        penalidades_list.setModel(listModel);
    }
    
    private String[] getNomePenalidade () {
        String penalidades_nome[] = new String[penalidades.size()];
        
        for (int i=0; i<penalidades.size(); i++) {
            Penalidade penalidade = penalidades.get(i);
            penalidades_nome[i] = penalidade.getNome();
        }
        
        return penalidades_nome;
    }
    
    private void penal_tempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penal_tempoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penal_tempoActionPerformed

    private void penal_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penal_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_penal_nomeActionPerformed

    private void penal_tempoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_penal_tempoFocusLost
        if (penal_tempo.getText().indexOf(":") < 0)
            penal_tempo.setText(penal_tempo.getText().substring(0, 2) + ":" + penal_tempo.getText().substring(2));
        
        if (penal_tempo.getText().length() > 5) {
            penal_tempo.setText("00:15");
        }
    }//GEN-LAST:event_penal_tempoFocusLost
    
    public Date converterData() {
        Date data = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        
        String data_t = data_text.getText().trim();
        
        if (data_t.indexOf("/") < 0 && data_t.isEmpty() == false)
          data_t = data_t.substring(0, 2) + "/" + data_t.substring(2, 4) + "/" + data_t.substring(4);
        
        if (data_t.length() < 8 || data_t.length() > 10 || data_t.length() == 7 || data_t.length() == 9)
            data_t = "";
        
        if (data_t.isEmpty() == false) {
            if (data_t.length() == 8)
                data_t = data_t.substring(0, 6) + "20" + data_t.substring(6);
            
            try {
                System.out.println("Data4: " + data_t);
                data = dateFormat.parse(data_t);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, "Formato de data inválido. Por favor, insira a data no formato dd/MM/yyyy.");
                e.printStackTrace();
            }
        }
        
        return data;
    }
    
    public void setEquipe(Equipe e) {
        equipes.add(e);
    }
    
    public void setProva (Prova p) {
        provas.add(p);
    }
    
    public int sizeEquipe () {
        return equipes.size();
    }
    
    public int sizeProva () {
        return provas.size();
    }
    
    public void carregarEquipes () {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        String[] nomes = new String[equipes.size()];
        nomes = getEquipesNome();
        for(int i=0; i<nomes.length; i++) {
            listModel.addElement(nomes[i]);
        }
        
        equipes_list.setModel(listModel);
    }
    
    public void carregarProvas () {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        String[] nomes = new String[provas.size()];
        nomes = getProvasNome();
        for(int i=0; i<nomes.length; i++) {
            listModel.addElement(nomes[i]);
        }
        
        provas_list.setModel(listModel);
    }
    
    public String[] getEquipesNome() {
        String equipes_nome[] = new String[equipes.size()];
        
        for (int i=0; i<equipes.size(); i++) {
            Equipe equipe = equipes.get(i);
            equipes_nome[i] = equipe.getNome();
        }
        
        return equipes_nome;
    }
    
    public String[] getProvasNome() {
        String provas_nome[] = new String[provas.size()];
        
        for (int i=0; i<provas.size(); i++) {
            Prova prova = provas.get(i);
            provas_nome[i] = prova.getNome();
        }
        
        return provas_nome;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel data_label;
    private javax.swing.JPanel data_panel;
    private javax.swing.JTextField data_text;
    private javax.swing.JLabel equipes_label;
    private javax.swing.JList<String> equipes_list;
    private javax.swing.JPanel equipes_panel;
    private javax.swing.JButton inserir_equipe_button;
    private javax.swing.JButton inserir_prova_button;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nome_label;
    private javax.swing.JPanel nome_panel;
    private javax.swing.JTextField nome_text;
    private javax.swing.JLabel penal_label;
    private javax.swing.JTextField penal_nome;
    private javax.swing.JPanel penal_panel;
    private javax.swing.JTextField penal_tempo;
    private javax.swing.JButton penalidade_button;
    private javax.swing.JLabel penalidade_label;
    private javax.swing.JPanel penalidade_panel;
    private javax.swing.JList<String> penalidades_list;
    private javax.swing.JLabel provas_label;
    private javax.swing.JList<String> provas_list;
    private javax.swing.JPanel provas_panel;
    private javax.swing.JButton save_button;
    // End of variables declaration//GEN-END:variables
}
