/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uri.robomatch.interfaces;

import com.uri.robomatch.*;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author julia
 */
public class RoboMatchJFrame extends javax.swing.JFrame {
    private Competicao competicao;
    private Placar placar;
    private ArrayList<Competicao> competicoes = new ArrayList<>();
            
    public RoboMatchJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        competicao_panel.setVisible(false);
        voltar_button.setVisible(false);
        iniciar_button.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicio_panel = new javax.swing.JPanel();
        competicao_button = new javax.swing.JButton();
        padroes_button = new javax.swing.JButton();
        voltar_button = new javax.swing.JButton();
        competicao_panel = new javax.swing.JPanel();
        inserir_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        competicao_list = new javax.swing.JList<>();
        iniciar_button = new javax.swing.JButton();
        titulo_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 350));

        competicao_button.setText("Competições");
        competicao_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                competicao_buttonMouseClicked(evt);
            }
        });

        padroes_button.setText("Inicializar informações");
        padroes_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                padroes_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout inicio_panelLayout = new javax.swing.GroupLayout(inicio_panel);
        inicio_panel.setLayout(inicio_panelLayout);
        inicio_panelLayout.setHorizontalGroup(
            inicio_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_panelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(competicao_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(padroes_button)
                .addGap(30, 30, 30))
        );
        inicio_panelLayout.setVerticalGroup(
            inicio_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicio_panelLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addGroup(inicio_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(competicao_button)
                    .addComponent(padroes_button))
                .addGap(120, 120, 120))
        );

        voltar_button.setText("Voltar");
        voltar_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltar_buttonMouseClicked(evt);
            }
        });

        inserir_button.setText("Inserir +");
        inserir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserir_buttonActionPerformed(evt);
            }
        });

        competicao_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        competicao_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                competicao_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(competicao_list);

        iniciar_button.setText("Iniciar");
        iniciar_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iniciar_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout competicao_panelLayout = new javax.swing.GroupLayout(competicao_panel);
        competicao_panel.setLayout(competicao_panelLayout);
        competicao_panelLayout.setHorizontalGroup(
            competicao_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(competicao_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(competicao_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(competicao_panelLayout.createSequentialGroup()
                        .addComponent(iniciar_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inserir_button))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, competicao_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        competicao_panelLayout.setVerticalGroup(
            competicao_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(competicao_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(competicao_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciar_button)
                    .addComponent(inserir_button))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        titulo_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titulo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_label.setText("RoboMatch");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inicio_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(competicao_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(voltar_button)
                        .addGap(53, 53, 53)
                        .addComponent(titulo_label)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo_label)
                    .addComponent(voltar_button))
                .addGap(40, 40, 40)
                .addComponent(inicio_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(competicao_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void competicao_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_competicao_buttonMouseClicked
        titulo_label.setText("Competições");
        
        inicio_panel.setVisible(false);
        competicao_panel.setVisible(true);
        voltar_button.setVisible(true);
        
        carregarCompeticoes();
    }//GEN-LAST:event_competicao_buttonMouseClicked

    private void inserir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserir_buttonActionPerformed
        CompeticaoJFrame competicao_frame = new CompeticaoJFrame(this);
        competicao_frame.setVisible(true);
    }//GEN-LAST:event_inserir_buttonActionPerformed

    private void voltar_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltar_buttonMouseClicked
        titulo_label.setText("Placar de Competições");
        
        inicio_panel.setVisible(true);
        competicao_panel.setVisible(false);
        voltar_button.setVisible(false);
        iniciar_button.setVisible(false);
    }//GEN-LAST:event_voltar_buttonMouseClicked

    private void padroes_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_padroes_buttonMouseClicked
        padroes_button.setVisible(false);
        
        Equipe e1, e2, e3;
        Prova p1, p2, p3;
        Competicao c1;
        Penalidade pn1, pn2, pn3;
        
        e1 = new Equipe("Equipe ABC");
        e2 = new Equipe("Equipe 123");
        e3 = new Equipe("Equipe XXX");
        
        p1 = new Prova(1, "Prova 1", 30, 200);
        p2 = new Prova(2, "Prova 2", 60, 200);
        p3 = new Prova(3, "Prova 3", 90, 200);
        
        pn1 = new Penalidade("Penalidade 1 - 5seg", 5);
        pn2 = new Penalidade("Penalidade 2 - 10seg", 10);
        pn3 = new Penalidade("Penalidade 3 - 15seg", 15);
        
        c1 = new Competicao("Competição de Robótica - URI", new java.util.Date());
        
        c1.setEquipe(e1);
        c1.setEquipe(e2);
        c1.setEquipe(e3);
        
        c1.setProva(p1);
        c1.setProva(p2);
        c1.setProva(p3);
        
        c1.setPenalidade(pn1);
        c1.setPenalidade(pn2);
        c1.setPenalidade(pn3);
        
        setCompeticao(c1);
    }//GEN-LAST:event_padroes_buttonMouseClicked

    private void competicao_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_competicao_listMouseClicked
        iniciar_button.setVisible(true);
    }//GEN-LAST:event_competicao_listMouseClicked

    private void iniciar_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iniciar_buttonMouseClicked
        int index = competicao_list.getSelectedIndex();
        competicao = competicoes.get(index);
                
        placar = new Placar(competicao);
        
        CompeticaoIniciar comp_iniciar = new CompeticaoIniciar(competicao, placar);
        comp_iniciar.setVisible(true);
    }//GEN-LAST:event_iniciar_buttonMouseClicked
    
    public void setCompeticao (Competicao c) {
        competicoes.add(c);
    }
    
    public int sizeCompeticoes () {
        return competicoes.size();
    }
    
    public void carregarCompeticoes () {
        DefaultListModel<String> listModel = new DefaultListModel<>();
        String[] nomes = new String[competicoes.size()];
        nomes = getCompeticoesNome();
        for(int i=0; i<nomes.length; i++) {
            listModel.addElement(nomes[i]);
        }
        
        competicao_list.setModel(listModel);
    }
    
    public String[] getCompeticoesNome() {
        String competicoes_nome[] = new String[competicoes.size()];
        
        int i = 0;
        for (Competicao competicao : competicoes) {
            competicoes_nome[i] = competicao.getNome();
            System.out.println("Competição nome: " + competicao.getNome());
            i += 1;
        }
        
        return competicoes_nome;
    }
    /*
    public static void main(String args[]) { */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoboMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoboMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoboMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoboMatchJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold> */
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoboMatchJFrame().setVisible(true);
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton competicao_button;
    private javax.swing.JList<String> competicao_list;
    private javax.swing.JPanel competicao_panel;
    private javax.swing.JButton iniciar_button;
    private javax.swing.JPanel inicio_panel;
    private javax.swing.JButton inserir_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton padroes_button;
    private javax.swing.JLabel titulo_label;
    private javax.swing.JButton voltar_button;
    // End of variables declaration//GEN-END:variables
}
